# Generated by Django 4.2.7 on 2023-11-22 18:12

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('stocks', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Transaction',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('price', models.IntegerField()),
                ('quantity', models.IntegerField()),
                ('order_type', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to='stocks.order')),
                ('stock_name', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to='stocks.stock')),
            ],
        ),
    ]
