# Generated by Django 4.2.7 on 2023-11-22 18:14

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('stocks', '0002_transaction'),
    ]

    operations = [
        migrations.AlterField(
            model_name='transaction',
            name='order_type',
            field=models.ForeignKey(on_delete=django.db.models.deletion.DO_NOTHING, to='stocks.order'),
        ),
        migrations.AlterField(
            model_name='transaction',
            name='stock_name',
            field=models.ForeignKey(on_delete=django.db.models.deletion.DO_NOTHING, to='stocks.stock'),
        ),
    ]
