# Generated by Django 4.2.7 on 2023-11-22 18:19

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('stocks', '0003_alter_transaction_order_type_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='order',
            name='stock_name',
            field=models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to='stocks.stock'),
        ),
        migrations.AlterField(
            model_name='transaction',
            name='order_type',
            field=models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to='stocks.order'),
        ),
        migrations.AlterField(
            model_name='transaction',
            name='stock_name',
            field=models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to='stocks.stock'),
        ),
    ]
