# Generated by Django 4.2.7 on 2023-11-23 10:34

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('stocks', '0003_alter_inventory_owner'),
    ]

    operations = [
        migrations.AlterField(
            model_name='order',
            name='order_type',
            field=models.CharField(choices=[('Buy', 'Buy'), ('Sell', 'Sell')], max_length=4),
        ),
    ]
