# Generated by Django 4.2.7 on 2023-11-23 10:39

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('stocks', '0004_alter_order_order_type'),
    ]

    operations = [
        migrations.AddField(
            model_name='order',
            name='time',
            field=models.DateTimeField(default=datetime.datetime(2023, 11, 23, 10, 39, 55, 607221)),
        ),
    ]
