# Generated by Django 4.2.7 on 2023-11-23 10:54

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('stocks', '0005_order_time'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='order',
            options={'ordering': ('time',)},
        ),
        migrations.AlterField(
            model_name='order',
            name='time',
            field=models.DateTimeField(default=datetime.datetime(2023, 11, 23, 10, 54, 59, 196236)),
        ),
    ]
