version: "3.1"

services:
  backend:
    build: ./backend
    restart: always
    command: python manage.py runserver 0.0.0.0:8000
    container_name: backend
    volumes:
      - ./backend/:/backend/
#    depends_on:
#      - db
    ports:
      - 8000:8000

#  db:
#    image: postgres
#    restart: always
#    container_name: postgresql
#    environment:
#      POSTGRES_USER: test_task_user
#      POSTGRES_PASSWORD: dbpass
#    ports:
#      - 5432:5432

  redis:
    image: redis:5.0.1-alpine
    container_name: redis
    restart: unless-stopped
    expose:
      - 6379

  celery:
    build: ./backend
    container_name: celery
    restart: unless-stopped
    command: celery -A backend worker --beat -l INFO
    environment:
      CELERY_BROKER_URL: "redis://redis:6379"
      CELERY_RESULT_BACKEND: "redis://redis:6379"

  frontend:
    build: ./frontend
    restart: always
    container_name: frontend
    command: npm start
    ports:
      - 3000:3000